# Generated by Django 2.2.3 on 2019-07-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'escuela',
            },
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'palabraclave',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('psw', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesis.Escuela')),
                ('palabraclave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesis.PalabraClave')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesis.Tutor')),
            ],
            options={
                'db_table': 'tg',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesis.Tesis')),
                ('userCreado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreado', to='tesis.Usuario')),
                ('userCreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreador', to='tesis.Usuario')),
            ],
            options={
                'db_table': 'audit',
            },
        ),
    ]
