# Generated by Django 2.2.3 on 2019-07-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesis',
            name='tutor',
        ),
    ]
