# Generated by Django 2.2.3 on 2019-07-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.IntegerField(unique=True)),
                ('es_tutor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'evaluador',
            },
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='palabraclave',
        ),
        migrations.AddField(
            model_name='tesis',
            name='palabasclave',
            field=models.ManyToManyField(to='tesis.PalabraClave'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='tesis.Evaluador'),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.AddField(
            model_name='tesis',
            name='evaluadores',
            field=models.ManyToManyField(related_name='evaluadores', to='tesis.Evaluador'),
        ),
    ]
