# Generated by Django 2.2.3 on 2019-07-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesis',
            old_name='palabasclave',
            new_name='palabrasclave',
        ),
    ]
