# Generated by Django 2.2.3 on 2019-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0003_auto_20190715_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_creador',
            field=models.IntegerField(null=True),
        ),
    ]
