# Generated by Django 2.2.3 on 2019-07-15 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0003_auto_20190714_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='tesis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tesis.Tesis'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='userCreado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCreado', to=settings.AUTH_USER_MODEL),
        ),
    ]
